#!/usr/bin/env python3
"""Point Claude Code at TimoRouter by picking models from models.json.

The model list comes from this repo's models.json (regenerated by
tools/sync-models.py on the server). This script only rewrites the
model-related keys in ~/.claude/settings.json; everything else
(hooks, attribution, timeouts, ...) is preserved.

Interactive (default):

    python3 claude/sync.py

Non-interactive:

    python3 claude/sync.py --non-interactive \
        --fable <id> --opus <id> --sonnet <id> --haiku <id> \
        --base-url http://127.0.0.1:8317 --token <token> \
        [--config PATH] [--models-url URL]

Stdlib only. Never writes secrets anywhere except the user's own config.
"""
import argparse
import datetime
import getpass
import json
import os
import shutil
import sys
import urllib.request

MODELS_URL = "https://raw.githubusercontent.com/timothy0509/TimoRouter-model-list/main/models.json"
LOCAL_DEFAULT_URL = "http://127.0.0.1:8317"
REMOTE_DEFAULT_URL = "https://timopc.tailc18075.ts.net:8317"

# (slot label, env var) in prompt order.
SLOTS = (
    ("fable", "ANTHROPIC_DEFAULT_FABLE_MODEL"),
    ("opus", "ANTHROPIC_DEFAULT_OPUS_MODEL"),
    ("sonnet", "ANTHROPIC_DEFAULT_SONNET_MODEL"),
    ("haiku", "ANTHROPIC_DEFAULT_HAIKU_MODEL"),
)


def default_config_path():
    return os.path.join(os.path.expanduser("~"), ".claude", "settings.json")


def fetch_models(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        doc = json.loads(r.read().decode("utf-8"))
    models = doc.get("models", [])
    if not models:
        raise ValueError("models.json contained no models, refusing to touch config")
    ids = [m["id"] for m in models]
    if len(set(ids)) != len(ids):
        raise ValueError("models.json contained duplicate model ids")
    return models


def load_settings(path):
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        cfg = json.load(f)
    if not isinstance(cfg, dict):
        raise ValueError(f"{path} does not contain a JSON object")
    return cfg


def backup_settings(path):
    if not os.path.exists(path):
        return None
    stamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    backup = f"{path}.bak-claude-{stamp}"
    shutil.copy2(path, backup)
    # Keep only the 5 newest backups.
    dirname = os.path.dirname(path) or "."
    basename = os.path.basename(path)
    keep = sorted(
        p for p in os.listdir(dirname)
        if p.startswith(basename + ".bak-claude-")
    )
    for old in keep[:-5]:
        try:
            os.remove(os.path.join(dirname, old))
        except OSError:
            pass
    return backup


def write_settings(path, cfg):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")


def base_reachable(base_url):
    import socket
    try:
        probe = base_url.rstrip("/") + "/v1/models"
        urllib.request.urlopen(probe, timeout=2).close()
        return True
    except urllib.error.HTTPError:
        # Any HTTP response (even 401/404) means the server is up.
        return True
    except (urllib.error.URLError, socket.timeout, OSError, ValueError):
        return False


def prompt(text, default=None, secret=False):
    suffix = f" [{default}]" if default and not secret else ""
    if secret and default:
        suffix = " [keep existing]"
    reader = (lambda p: getpass.getpass(p)) if secret else input
    while True:
        try:
            val = reader(f"{text}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print(file=sys.stderr)
            sys.exit(130)
        if val:
            return val
        if default is not None:
            return default
        print("a value is required.")


def describe(entry):
    bits = [entry.get("display_name") or entry["id"]]
    if entry.get("context_window"):
        bits.append(f"ctx {entry['context_window']}")
    if entry.get("reasoning_default"):
        bits.append(f"reasoning {entry['reasoning_default']}")
    return " | ".join(bits)


def pick_interactive(slot, env_key, models, current):
    print(f"\n--- {slot} ({env_key}) ---")
    for i, entry in enumerate(models, 1):
        marker = "  <-- current" if entry["id"] == current else ""
        print(f"  {i:>3}. {entry['id']}  ({describe(entry)}){marker}")
    valid = {e["id"] for e in models}
    while True:
        raw = prompt(f"pick {slot} model (number or id)", current or models[0]["id"])
        if raw.isdigit() and 1 <= int(raw) <= len(models):
            return models[int(raw) - 1]["id"]
        if raw in valid:
            return raw
        print(f"unknown model {raw!r}; enter a number 1-{len(models)} or a valid id.")


def validate_ids(models, picks):
    valid = {e["id"] for e in models}
    bad = {slot: mid for slot, mid in picks.items() if mid not in valid}
    if bad:
        for slot, mid in bad.items():
            print(f"error: unknown model id for --{slot}: {mid!r}", file=sys.stderr)
        print(f"hint: valid ids come from the fetched models.json "
              f"({len(valid)} models).", file=sys.stderr)
        sys.exit(2)


def apply_picks(cfg, picks, base_url, token):
    """Merge model choices into a settings dict, preserving everything else."""
    env = cfg.setdefault("env", {})
    old_sonnet = env.get("ANTHROPIC_DEFAULT_SONNET_MODEL")
    for slot, env_key in SLOTS:
        env[env_key] = picks[slot]
    # Derived keys follow the workhorse / fast slots.
    env["ANTHROPIC_MODEL"] = picks["sonnet"]
    env["ANTHROPIC_SMALL_FAST_MODEL"] = picks["haiku"]
    env["CLAUDE_CODE_SUBAGENT_MODEL"] = picks["haiku"]
    if base_url is not None:
        env["ANTHROPIC_BASE_URL"] = base_url
    if token is not None:
        env["ANTHROPIC_AUTH_TOKEN"] = token
    cfg["model"] = picks["sonnet"]
    cfg["fallbackModel"] = [picks["sonnet"]]
    settings = cfg.setdefault("modelSettings", {})
    if picks["sonnet"] not in settings:
        if old_sonnet and old_sonnet in settings:
            settings[picks["sonnet"]] = settings[old_sonnet]
        else:
            settings[picks["sonnet"]] = {"effortLevel": "high"}
    return cfg


def do_interactive(args):
    models = fetch_models(args.models_url)
    print(f"fetched {len(models)} models from {args.models_url}")
    cfg = load_settings(args.config)
    env = cfg.get("env", {})

    picks = {}
    fallback_current = (env.get("ANTHROPIC_DEFAULT_SONNET_MODEL")
                        or env.get("ANTHROPIC_MODEL")
                        or (cfg.get("model") if isinstance(cfg.get("model"), str) else None))
    for slot, env_key in SLOTS:
        current = env.get(env_key) or (fallback_current if slot != "haiku" else None)
        if slot == "haiku":
            current = (env.get(env_key) or env.get("ANTHROPIC_SMALL_FAST_MODEL")
                       or env.get("CLAUDE_CODE_SUBAGENT_MODEL") or fallback_current)
        picks[slot] = pick_interactive(slot, env_key, models, current)

    default_url = (env.get("ANTHROPIC_BASE_URL")
                   or (LOCAL_DEFAULT_URL if base_reachable(LOCAL_DEFAULT_URL)
                       else REMOTE_DEFAULT_URL))
    base_url = prompt("CliProxyAPI base URL", default_url)
    token = prompt("Your CliProxyAPI auth token",
                   env.get("ANTHROPIC_AUTH_TOKEN"), secret=True)

    apply_picks(cfg, picks, base_url, token)
    backup = backup_settings(args.config)
    write_settings(args.config, cfg)
    print(f"\nwrote {args.config}" + (f" (backup: {backup})" if backup else ""))
    for slot, env_key in SLOTS:
        print(f"  {env_key}={picks[slot]}")
    print(f"  model={picks['sonnet']} fallbackModel=[{picks['sonnet']}]")
    return 0


def do_non_interactive(args):
    models = fetch_models(args.models_url)
    cfg = load_settings(args.config)
    env = cfg.get("env", {})

    picks = {
        "fable": args.fable,
        "opus": args.opus,
        "sonnet": args.sonnet,
        "haiku": args.haiku,
    }
    # Slots not given on the CLI fall back to the existing config so a
    # partial invocation only changes what was asked for.
    for slot, env_key in SLOTS:
        if not picks[slot]:
            picks[slot] = (env.get(env_key) or picks.get("sonnet")
                           or env.get("ANTHROPIC_MODEL"))
    if not picks["sonnet"] or not picks["haiku"]:
        print("error: --non-interactive needs at least --sonnet and --haiku "
              "(or an existing config with those values).", file=sys.stderr)
        return 2
    # Unspecified big slots follow sonnet; unspecified fable follows opus.
    picks["opus"] = picks["opus"] or picks["sonnet"]
    picks["fable"] = picks["fable"] or picks["opus"]
    validate_ids(models, picks)

    base_url = (args.base_url or env.get("ANTHROPIC_BASE_URL")
                or (LOCAL_DEFAULT_URL if base_reachable(LOCAL_DEFAULT_URL)
                    else REMOTE_DEFAULT_URL))
    token = args.token or env.get("ANTHROPIC_AUTH_TOKEN")
    if not token:
        print("error: --non-interactive needs --token "
              "(or an existing ANTHROPIC_AUTH_TOKEN).", file=sys.stderr)
        return 2

    apply_picks(cfg, picks, base_url, token)
    backup = backup_settings(args.config)
    write_settings(args.config, cfg)
    print(f"wrote {args.config}" + (f" (backup: {backup})" if backup else ""))
    for slot, env_key in SLOTS:
        print(f"  {env_key}={picks[slot]}")
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Sync TimoRouter models into ~/.claude/settings.json")
    ap.add_argument("--models-url", default=MODELS_URL)
    ap.add_argument("--config", default=default_config_path())
    ap.add_argument("--non-interactive", action="store_true")
    ap.add_argument("--fable", default=None)
    ap.add_argument("--opus", default=None)
    ap.add_argument("--sonnet", default=None)
    ap.add_argument("--haiku", default=None)
    ap.add_argument("--base-url", default=None)
    ap.add_argument("--token", default=None)
    args = ap.parse_args(argv)

    try:
        if args.non_interactive:
            return do_non_interactive(args)
        return do_interactive(args)
    except (ValueError, urllib.error.URLError, OSError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
