#!/usr/bin/env python3
"""Sync Codex config (config.toml) + model catalog from models.json.

Source of truth for the model list: this repo's models.json
(regenerated by tools/sync-models.py on the server), fetched from
--models-url. This script performs text surgery on config.toml so that
unknown sections ([projects.*], [hooks.*], [tui.*], [notice.*], ...)
are left byte-for-byte untouched. Only managed keys/blocks change:

  top-level:            model_provider, model, model_catalog_json,
                        model_reasoning_effort
  [agents]:             default_subagent_model (+ reasoning effort)
  [model_providers.custom]: name, base_url, wire_api,
                        requires_openai_auth, experimental_bearer_token
  [profiles.zen_*]:     one canonical table per model in models.json;
                        stale tables removed, each table's model +
                        model_reasoning_effort updated
  <catalog json>:       fully regenerated, one entry per model

Stdlib only. Backs up config.toml + catalog before writing.
"""
import argparse
import datetime
import getpass
import json
import os
import re
import shutil
import sys
import urllib.request

MODELS_URL = ("https://raw.githubusercontent.com/"
              "timothy0509/TimoRouter-model-list/main/models.json")
DEFAULT_BASE_URL = "http://127.0.0.1:8317/v1/"
REMOTE_BASE_URL = "https://timopc.tailc18075.ts.net:8317/v1/"
PREFERRED_DEFAULT_MODEL = "muse-spark-1.3-contributor"
PROVIDER_NAME = "CLIProxyAPI local"
FALLBACK_CONTEXT_WINDOW = 256000

BASE_INSTRUCTIONS = ("You are Codex, a coding agent. You and the user share "
                     "the same workspace and collaborate to achieve the "
                     "user's goals.")

EFFORT_DESCRIPTIONS = {
    "minimal": "Minimal reasoning",
    "low": "Fast responses with lighter reasoning",
    "medium": "Balances speed and reasoning depth for everyday tasks",
    "high": "Greater reasoning depth for complex problems",
    "xhigh": "Extra high reasoning depth for complex problems",
    "max": "Maximum reasoning depth for the hardest problems",
    "none": "Disable Thinking",
}

SECTION_HDR = re.compile(r"(?m)^\[[^\]\n]+\]\s*$")
ZEN_PROFILE_HDR = re.compile(r"(?m)^\[profiles\.zen_[A-Za-z0-9_]+\]\s*$")
MODEL_ID_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")


def default_codex_home():
    return os.path.expanduser("~/.codex")


def sanitize_slug(model_id):
    return re.sub(r"[^a-z0-9]+", "_", model_id.lower()).strip("_") or "model"


def toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fetch_models(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        doc = json.loads(r.read().decode("utf-8"))
    models = doc.get("models", [])
    if not models:
        raise ValueError("models.json contained no models, refusing to touch config")
    seen = set()
    for e in models:
        mid = e.get("id")
        if not isinstance(mid, str) or not MODEL_ID_RE.fullmatch(mid):
            raise ValueError(f"invalid model id in models.json: {mid!r}")
        if mid in seen:
            raise ValueError(f"duplicate model id in models.json: {mid!r}")
        seen.add(mid)
    return models


def backup_file(path):
    if not os.path.exists(path):
        return None
    stamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    backup = f"{path}.bak-codex-sync-{stamp}"
    shutil.copy2(path, backup)
    return backup


def read_text(path):
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as f:
        return f.read()


def write_text(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
        if not text.endswith("\n"):
            f.write("\n")


def split_header(text):
    """Return (top_level_header, rest) split at the first section header."""
    m = SECTION_HDR.search(text)
    if not m:
        return text, ""
    return text[:m.start()], text[m.start():]


def set_key_in_text(block, key, value_toml):
    pat = re.compile(r"(?m)^" + re.escape(key) + r"\s*=.*$")
    line = f"{key} = {value_toml}"
    if pat.search(block):
        return pat.sub(line, block, count=1)
    if block and not block.endswith("\n"):
        block += "\n"
    return block + line + "\n"


def remove_key_in_text(block, key):
    pat = re.compile(r"(?m)^" + re.escape(key) + r"\s*=.*$\n?")
    return pat.sub("", block, count=1)


def find_block(text, name):
    hdr = re.compile(r"(?m)^\[" + re.escape(name) + r"\]\s*$")
    m = hdr.search(text)
    if not m:
        return None
    nxt = SECTION_HDR.search(text, m.end())
    end = nxt.start() if nxt else len(text)
    return (m.start(), end)


def ensure_section(text, name):
    if find_block(text, name) is None:
        if text and not text.endswith("\n"):
            text += "\n"
        if text and not text.endswith("\n\n"):
            text += "\n"
        text += f"[{name}]\n"
    return text


def set_key_in_section(text, section, key, value_toml):
    text = ensure_section(text, section)
    span = find_block(text, section)
    start, end = span
    block = set_key_in_text(text[start:end], key, value_toml)
    return text[:start] + block + text[end:]


def remove_key_in_section(text, section, key):
    span = find_block(text, section)
    if span is None:
        return text
    start, end = span
    block = remove_key_in_text(text[start:end], key)
    return text[:start] + block + text[end:]


def set_top_level(text, key, value_toml):
    header, rest = split_header(text)
    return set_key_in_text(header, key, value_toml) + rest


def remove_top_level(text, key):
    header, rest = split_header(text)
    return remove_key_in_text(header, key) + rest


def zen_profile_models(text):
    """Map existing [profiles.zen_*] section name -> model id (or None)."""
    out = {}
    for m in ZEN_PROFILE_HDR.finditer(text):
        nxt = SECTION_HDR.search(text, m.end())
        end = nxt.start() if nxt else len(text)
        mm = re.search(r'(?m)^model\s*=\s*"([^"]*)"', text[m.start():end])
        out[m.group(0)[1:-1]] = mm.group(1) if mm else None
    return out


def remove_all_zen_profiles(text):
    spans = []
    for m in ZEN_PROFILE_HDR.finditer(text):
        nxt = SECTION_HDR.search(text, m.end())
        end = nxt.start() if nxt else len(text)
        spans.append((m.start(), end))
    for start, end in reversed(spans):
        text = text[:start] + text[end:]
    return text, len(spans)


def append_zen_profiles(text, models):
    if text and not text.endswith("\n"):
        text += "\n"
    if text.strip() and not text.endswith("\n\n"):
        text += "\n"
    first = True
    for e in sorted(models, key=lambda m: m["id"]):
        slug = sanitize_slug(e["id"])
        if not first:
            text += "\n"
        first = False
        text += f"[profiles.zen_{slug}]\n"
        text += f"model = {toml_str(e['id'])}\n"
        text += 'model_provider = "custom"\n'
        if e.get("reasoning_default"):
            text += f"model_reasoning_effort = {toml_str(e['reasoning_default'])}\n"
    return text


def catalog_entry(e):
    ctx = e.get("context_window") or FALLBACK_CONTEXT_WINDOW
    levels = e.get("reasoning_levels") or []
    default = e.get("reasoning_default") or (levels[0] if levels else "medium")
    modalities = e.get("input") or ["text"]
    return {
        "additional_speed_tiers": [],
        "availability_nux": None,
        "base_instructions": BASE_INSTRUCTIONS,
        "context_window": ctx,
        "default_reasoning_level": default,
        "default_reasoning_summary": "none",
        "description": e.get("display_name") or e["id"],
        "display_name": e.get("display_name") or e["id"],
        "effective_context_window_percent": 95,
        "experimental_supported_tools": [],
        "input_modalities": modalities,
        "max_context_window": ctx,
        "priority": 1000,
        "service_tiers": [],
        "shell_type": "shell_command",
        "slug": e["id"],
        "support_verbosity": False,
        "supported_in_api": True,
        "supported_reasoning_levels": [
            {"description": EFFORT_DESCRIPTIONS.get(lv, lv), "effort": lv}
            for lv in levels
        ],
        "supports_image_detail_original": False,
        "supports_parallel_tool_calls": False,
        "supports_reasoning_summaries": True,
        "supports_search_tool": False,
        "truncation_policy": {"limit": 10000, "mode": "bytes"},
        "upgrade": None,
        "visibility": "list",
        "multi_agent_version": "v1",
        "use_responses_lite": False,
    }


def existing_provider_value(text, key):
    span = find_block(text, "model_providers.custom")
    if span is None:
        return None
    block = text[span[0]:span[1]]
    m = re.search(r'(?m)^' + re.escape(key) + r'\s*=\s*"([^"]*)"', block)
    return m.group(1) if m else None


def base_url_default(old_base):
    if old_base:
        return old_base
    try:
        urllib.request.urlopen(DEFAULT_BASE_URL + "models", timeout=2).close()
        return DEFAULT_BASE_URL
    except urllib.error.HTTPError:
        # Any HTTP response (even 401/404) means the local server is up.
        return DEFAULT_BASE_URL
    except (urllib.error.URLError, OSError, ValueError):
        return REMOTE_BASE_URL


def prompt(text, default=None, secret=False):
    suffix = f" [{default}]" if default else ""
    if secret:
        try:
            reader = getpass.getpass
        except Exception:  # noqa: BLE001 - fall back to visible input
            reader = input
    else:
        reader = input
    while True:
        val = reader(f"{text}{suffix}: ").strip()
        if val:
            return val
        if default is not None:
            return default
        print("a value is required.")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Sync Codex config.toml + model catalog from models.json")
    ap.add_argument("--models-url", default=MODELS_URL)
    ap.add_argument("--codex-home", default=default_codex_home())
    ap.add_argument("--config", default=None)
    ap.add_argument("--catalog", default=None)
    ap.add_argument("--base-url", default=None)
    ap.add_argument("--token", default=None)
    ap.add_argument("--model", default=None)
    ap.add_argument("--non-interactive", action="store_true",
                    help="never prompt; use flags/defaults/existing values")
    args = ap.parse_args(argv)

    config_path = args.config or os.path.join(args.codex_home, "config.toml")
    catalog_path = (args.catalog
                    or os.path.join(args.codex_home, "models-multi-agent.json"))

    models = fetch_models(args.models_url)
    print(f"fetched {len(models)} models from {args.models_url}")
    by_id = {e["id"]: e for e in models}
    ids = set(by_id)

    if PREFERRED_DEFAULT_MODEL in ids:
        suggested_default = PREFERRED_DEFAULT_MODEL
    else:
        suggested_default = models[0]["id"]

    text = read_text(config_path)
    old_base = existing_provider_value(text, "base_url")
    old_token = existing_provider_value(text, "experimental_bearer_token")

    if args.non_interactive:
        base_url = args.base_url or base_url_default(old_base)
        token = args.token if args.token is not None else (old_token or "")
        default_model = args.model or suggested_default
    else:
        base_url = args.base_url or prompt(
            "CliProxyAPI base URL", base_url_default(old_base))
        if args.token is not None:
            token = args.token
        else:
            token = prompt("CliProxyAPI bearer token (experimental_bearer_token)",
                           old_token or "", secret=True)
        if args.model is not None:
            default_model = args.model
        else:
            while True:
                default_model = prompt("Default model id", suggested_default)
                if default_model in ids:
                    break
                print(f"unknown model {default_model!r}; "
                      f"pick one of: {', '.join(sorted(ids))}")

    if default_model not in ids:
        print(f"error: model {default_model!r} is not in models.json "
              f"({len(ids)} models).", file=sys.stderr)
        return 2
    effort = by_id[default_model].get("reasoning_default")

    # --- text surgery on config.toml ---
    old_zen = zen_profile_models(text)

    text = set_top_level(text, "model_provider", '"custom"')
    text = set_top_level(text, "model", toml_str(default_model))
    text = set_top_level(text, "model_catalog_json",
                         toml_str(os.path.basename(catalog_path)))
    if effort:
        text = set_top_level(text, "model_reasoning_effort", toml_str(effort))
    else:
        text = remove_top_level(text, "model_reasoning_effort")

    text = set_key_in_section(text, "agents", "enabled", "true")
    text = set_key_in_section(text, "agents", "default_subagent_model",
                              toml_str(default_model))
    if effort:
        text = set_key_in_section(text, "agents",
                                  "default_subagent_reasoning_effort",
                                  toml_str(effort))
    else:
        text = remove_key_in_section(text, "agents",
                                     "default_subagent_reasoning_effort")

    text = set_key_in_section(text, "model_providers.custom", "name",
                              toml_str(PROVIDER_NAME))
    text = set_key_in_section(text, "model_providers.custom", "base_url",
                              toml_str(base_url))
    text = set_key_in_section(text, "model_providers.custom", "wire_api",
                              '"responses"')
    text = set_key_in_section(text, "model_providers.custom",
                              "requires_openai_auth", "false")
    text = set_key_in_section(text, "model_providers.custom",
                              "experimental_bearer_token", toml_str(token))

    text, _ = remove_all_zen_profiles(text)
    text = append_zen_profiles(text, models)

    new_zen_models = set(by_id)
    old_zen_models = {v for v in old_zen.values() if v}
    added = sorted(new_zen_models - old_zen_models)
    removed = sorted(old_zen_models - new_zen_models)

    # --- regenerate catalog ---
    catalog = {"models": [catalog_entry(e)
                          for e in sorted(models, key=lambda m: m["id"])]}

    backup_cfg = backup_file(config_path)
    backup_cat = backup_file(catalog_path)
    write_text(config_path, text)
    os.makedirs(os.path.dirname(catalog_path) or ".", exist_ok=True)
    with open(catalog_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2)
        f.write("\n")

    print(f"default model: {default_model}"
          + (f" (reasoning_effort={effort})" if effort else " (no reasoning effort)"))
    print(f"profiles: {len(models)} total "
          f"(+{len(added)}, -{len(removed)})")
    if added:
        print(f"  added: {', '.join(added)}")
    if removed:
        print(f"  removed: {', '.join(removed)}")
    print(f"wrote {config_path}"
          + (f" (backup: {backup_cfg})" if backup_cfg else ""))
    print(f"wrote {catalog_path} ({len(models)} entries)"
          + (f" (backup: {backup_cat})" if backup_cat else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
